name: Publish version on GitHub Pages

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: install build dependencies
        run: |
          sudo apt-get install -y libpng-dev libatlas-base-dev libblas-dev libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev graphicsmagick build-essential g++-4.8
      - run: npm install
      - run: npm run build
      - run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: install build dependencies
        run: |
          sudo apt-get install -y libpng-dev libatlas-base-dev libblas-dev libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev graphicsmagick build-essential g++-4.8
      - run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./browser
          destination_dir: ./${{ env.RELEASE_VERSION }}
          keep_files: true
